# --- MYSQL LOCAL ---
spring.datasource.url=jdbc:mysql://localhost:3306/mancholita?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=acbonilla12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.user.name=admin
spring.security.user.password=admin123